In [1]:
time = float(input("cycling time in hours is: "))

def litres(time):
    x = time * 0.5
    return x
    if type(x) == float:
        def round_down(n, decimals=0):
            multiplier = 10 ** decimals
            return math.floor(n * multiplier) / multiplier
            return x
            print("he needs to drink" + x + "lts")
    else:
        print("he needs to drink" + x + "lts")
litres(time=time)

1.5

In [12]:
sum_mix(['3', 6, 6, 0, '5', 8, 5, '6', 2,'0'], 41)


NameError: name 'sum_mix' is not defined

In [13]:
import pandas as pd 
import numpy as np

In [21]:
# generate random integer values
from numpy.random import randint
# seed random number generator
# generate some integers
values = randint(0, 50, 10)
print(values)

# generate random integer values
from numpy.random import randint
# seed random number generator
# generate some integers
values = randint(0, 50, 10)
print(values)

[10 32 25 21 39 32 19 25 49 14]
[13 20 43  6 13 15 24  9  2  7]


In [37]:
from numpy.random import randint
arr = randint(0, 50, 10)
print(arr)

def sum_mix(arr, n):
    return(sum(arr))
    arr = []
    arr.append['3','5','7']
    type(arr)
    n = len(arr) 
  
ans = sum(arr) 
# display sum 
print ('Sum of the array is ', ans) 
# sum() is an inbuilt function in python that adds  
# all the elements in list,set and tuples and returns 
# the value  
# display sum 

[36 36 32 19  3 24 19 37 30 38]
Sum of the array is  274


In [39]:
def divide(a,b):
    a = float(input("first number : "))
    b = float(input("second number: "))
    result = a/b
    return result
    print(result)
divide(2,3)

0.449936628643853

In [40]:
a = float(input("first number : "))
b = float(input("second number: "))

def divide(a,b):
    result = a/b
    return result
    print(result)
divide(a=a,b=b)

0.01753424636887128

In [41]:
def divide(a,b):
    return float(a) / float(b)

In [47]:
def even_or_odd(number):
    if (number % 2) == 0:
        print("Even")
    else:
        print("Odd")
    return even_or_odd

even_or_odd(5)

Odd


<function __main__.even_or_odd(number)>

Good morning! Here's your coding interview problem for today.

This problem was recently asked by Google.

Given a list of numbers and a number k, return whether any two numbers from the list add up to k.

For example, given [10, 15, 3, 7] and k of 17, return true since 10 + 7 is 17.

Bonus: Can you do this in one pass?

In [62]:
list = [10, 15, 3, 7]
for x in list:
    if x+y == 17:
        print('True')
    else:
        print('Not 17')

True
Not 17
Not 17
Not 17


This problem was asked by Uber.

Given an array of integers, return a new array such that each element at index i of the new array is the product of all the numbers in the original array except the one at i.

For example, if our input was [1, 2, 3, 4, 5], the expected output would be [120, 60, 40, 30, 24]. If our input was [3, 2, 1], the expected output would be [2, 3, 6].

Follow-up: what if you can't use division?

In [85]:
from numpy.random import randint
arr = randint(0, 10, 5)
print(arr)

def multilpy_mix(arr):
    ans = []
    for x in arr:
        a = arr[0]*arr[1]*arr[2]*arr[3]
        b = arr[1]*arr[2]*arr[3]*arr[4]
        c = arr[2]*arr[3]*arr[4]*arr[0]
        d = arr[3]*arr[4]*arr[0]*arr[1]
        e = arr[4]*arr[0]*arr[1]*arr[2]
        ans = ans.append(a, b, c, d, e)

# display calculus 
print ('Result of the opertion is ', ans) 

[3 4 9 3 9]
Result of the opertion is  264


In [83]:
ans

264

In [87]:
import pandas as pd 
#This problem was asked by Google.

#Given the root to a binary tree, implement serialize(root), which serializes the tree into a string, and deserialize(s), which deserializes the string back into the tree.

#For example, given the following Node class

class Node:
    def __init__(self, val, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right
#The following test should pass:

node = Node('root', Node('left', Node('left.left')), Node('right'))
assert deserialize(serialize(node)).left.left.val == 'left.left'

NameError: name 'deserialize' is not defined

create a function that removes the first and last characters of a string. You're given one parameter, the original string. You don't have to worry with strings with less than two characters.

In [94]:
s = input ("Enter a string:")
def remove(s):
    s = s[1:-1]
    print(s)
    return remove
    print(remove)
remove(s)

ol


<function __main__.remove(s)>

Given an array of integers your solution should find the smallest integer.

For example:
Given [34, 15, 88, 2] your solution will return 2
Given [34, -345, -1, 100] your solution will return -345
You can assume, for the purpose of this kata, that the supplied array will not be empty.


In [95]:
def find_smallest_int(arr):
    arr = randint(-100, 100, 5)
    print(arr)
    arr.sort()
# printing the first element 
    print("Smallest element is:", *arr[:1])
find_smallest_int(arr=arr)

[-19 -98  -7  64   9]
Smallest element is: -98


We know the content of the evaporator (content in ml), the percentage of foam or gas lost every day (evap_per_day and the threshold (threshold) in percentage beyond which the evaporator is no longer useful. All numbers are strictly positive.

The program reports the nth day (as an integer) on which the evaporator will be out of use.

In [ ]:
def evaporator(content, evap_per_day, threshold):
    

return a new sorted merged list from K sorted lists, each with size N.

The time complexity for that would be O(KN log KN), since we have K * N total elements.
lists is [].
lists only contains empty lists: [[], [], []].
lists contains empty lists and non-empty lists: [[], [1], [1,2]].
lists contains one list with one element: [[1]].
lists contains lists of varying size: [[1], [1, 3, 5], [1, 10, 20, 30, 40]].

divide-and-conquer strategy


In [96]:
def merge(lists):
    merged_list = []

    heap = [(lst[0], i, 0) for i, lst in enumerate(lists) if lst]
    heapq.heapify(heap)

    while heap:
        val, list_ind, element_ind = heapq.heappop(heap)

        merged_list.append(val)

        if element_ind + 1 < len(lists[list_ind]):
            next_tuple = (lists[list_ind][element_ind + 1],
                          list_ind,
                          element_ind + 1)
            heapq.heappush(heap, next_tuple)
    return merged_list

This problem was asked by Airbnb.

Given a list of integers, write a function that returns the largest sum of non-adjacent numbers. Numbers can be 0 or negative.

For example, [2, 4, 6, 2, 5] should return 13, since we pick 2, 6, and 5. [5, 1, 1, 5] should return 10, since we pick 5 and 5.

Follow-up: Can you do this in O(N) time and constant space?

This problem was asked by Apple.

Implement a job scheduler which takes in a function f and an integer n, and calls f after n milliseconds.

Good morning! Here's your coding interview problem for today.

This problem was asked by Twitter.

Implement an autocomplete system. That is, given a query string s and a set of all possible query strings, return all strings in the set that have s as a prefix.

For example, given the query string de and the set of strings [dog, deer, deal], return [deer, deal].

Hint: Try preprocessing the dictionary into a more efficient data structure to speed up queries.

ood morning! Here's your coding interview problem for today.

This problem was asked by Amazon.

There exists a staircase with N steps, and you can climb up either 1 or 2 steps at a time. Given N, write a function that returns the number of unique ways you can climb the staircase. The order of the steps matters.

For example, if N is 4, then there are 5 unique ways:

1, 1, 1, 1
2, 1, 1
1, 2, 1
1, 1, 2
2, 2
What if, instead of being able to climb 1 or 2 steps at a time, you could climb any number from a set of positive integers X? For example, if X = {1, 3, 5}, you could climb 1, 3, or 5 steps at a time.