### PracticePython - Org

##Exercise 1 (and Solution)

#Create a program that asks the user to enter their name and their age. Print out a message addressed to them that tells them the year that they will turn 100 years old.

In [3]:
name = input("What's your name?")
age = input("How old are you?")
x = 100 - int(age)
year = 2020 + x
print(str(name) + " in " + str(year) + " you'll be 100 years old.")



RochiIn 2079 you'll be 100 years old.


### Extras:

Add on to the previous program by asking the user for another number and printing out that many copies of the previous message. (Hint: order of operations exists in Python)
Print out that many copies of the previous message on separate lines. (Hint: the string "\n is the same as pressing the ENTER button)

In [21]:
name = input("What's your name?")
age = input("How old are you?")
x = 100 - int(age)
year = 2020 + x

print(str(name) + " in " + str(year) + " you'll be 100 years old.")


rochi in 2079 you'll be 100 years old.


In [23]:
n = int(input("Enter any number"))
for i in range(x):
    print(str(name) + " in " + str(year) + " you'll be 100 years old.")

rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 100 years old.
rochi in 2079 you'll be 1

In [16]:
x = "4"
x*7

'4444444'

In [24]:
f = print(str(name) + " in " + str(year) + " you'll be 100 years old.")
f


rochi in 2079 you'll be 100 years old.


In [25]:
r ="Rochi in 2079 you'll be 100 years old.\n"
print(r*6)


Rochi in 2079 you'll be 100 years old.
Rochi in 2079 you'll be 100 years old.
Rochi in 2079 you'll be 100 years old.
Rochi in 2079 you'll be 100 years old.
Rochi in 2079 you'll be 100 years old.
Rochi in 2079 you'll be 100 years old.



##Exercise 2 (and Solution)
Ask the user for a number. Depending on whether the number is even or odd, print out an appropriate message to the user. 

#Hint: how does an even / odd number react differently when divided by 2?

In [45]:
number = int(input("Enter a number: "))

def pares(choice):
    if number %2 == 0:
        print("Good job! You chose an even number")
    else:
        print("Buuu. That's odd")
pares(choice=number)

Good job! You chose an even number


##Exercise 7 (and Solution)
Let’s say I give you a list saved in a variable: a = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]. Write one line of Python that takes this list a and makes a new list that has only the even elements of this list in it.

In [27]:
a = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [35]:
for n in a: [lambda a: a % 2]
print(a)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [36]:
a = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

b = [elem for elem in a if elem % 2 == 0] 
print(b)

[4, 16, 36, 64, 100]


##Exercise 14 (and Solution)
Write a program (function!) that takes a list and returns a new list that contains all the elements of the first list minus all the duplicates.

In [9]:
a = ["perro", "gato", "delfin", "mono", "perro", "caballo", "vaca", "vaca", "mono", "jirafa", "cerdo", "caballo"]

print(len(a))

12


In [10]:
a = ["perro", "gato", "delfin", "mono", "perro", "caballo", "vaca", "vaca", "mono", "jirafa", "cerdo", "caballo"]
b = []
def nuevalista(sindup):
    while elem in a:
        if elem == elem:
            print(elem, " repetido")
        else:
            b.append(elem)
            print(b)

nuevalista(sindup=b)

NameError: name 'elem' is not defined

In [38]:
a = ["perro", "gato", "delfin", "mono", "perro", "caballo", "vaca", "vaca", "mono", "jirafa", "cerdo", "caballo"]
b = []

def nuevalista(sindup):
    acum = 0
    while acum <= len(a) - 1:
        if a[acum] not in b:
            b.append(a[acum])
        acum += 1
    return b

nuevalista(sindup=a)

['perro', 'gato', 'delfin', 'mono', 'caballo', 'vaca', 'jirafa', 'cerdo']

In [40]:
a = ["perro", "gato", "delfin", "mono", "perro", "caballo", "vaca", "vaca", "mono", "jirafa", "cerdo", "caballo"]

def nuevalista(sindup):
    b = []
    for i in a:
        if i not in b:
            b.append(i)
    return b

nuevalista(sindup=b)


['perro', 'gato', 'delfin', 'mono', 'caballo', 'vaca', 'jirafa', 'cerdo']

##Extras:

Write two different functions to do this - one using a loop and constructing a list, and another using sets.
Go back and do Exercise 5 using sets, and write the solution for that in a different function.

In [60]:
a = ["perro", "gato", "delfin", "mono", "perro", "caballo", "vaca", "vaca", "mono", "jirafa", "cerdo", "caballo"]
b = []

def nuevalista(sindup):    
    return list(set(a))

nuevalista(sindup=b)

['delfin', 'vaca', 'caballo', 'perro', 'mono', 'jirafa', 'cerdo', 'gato']

In [ ]:
## Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull

In [96]:
number = "1038"
answer = "1253"
##answer = input("Insert a number:")

bulls_acum = 0
cows_acum = 0

while cows_acum < 4
    answer = input ("Insert a 4 digit number. If you want to quit the game, insert "STOP".")

    for pos, num in enumerate(number):
        if num == answer[pos]:
            cows_acum += 1
        elif num in answer:
            bulls_acum += 1
    if not cows_acum and not bulls_acum:
        print("Sorry. No cows or bulls.")

print("Cows: ", cows_acum)
print("Bulls: ", bulls_acum)


Cows:  1
Bulls:  1


In [90]:
##para lo toros (bulls)

x = "1234"
if "1" in x:
    print("Lo contiene")


Lo contiene


In [35]:
def dedupe_v2(x):
    return list(set(x))

a = [1,2,3,4,3,2,1]
print(a)
print(dedupe_v2(a))

[1, 2, 3, 4, 3, 2, 1]
[1, 2, 3, 4]


In [64]:
names = ["Michele", "Robin", "Sara", "Michele"]
names = set(names)
names = list(names)
print(names)

['Robin', 'Michele', 'Sara']


In [7]:
mapping = dict(zip(range(5), reversed(range(5))))
mapping


{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

In [60]:
some_dict = {0: 4, 1: 3, "telefono": 64023, 3: 1, 4: 0}


In [61]:
value = some_dict.get("telefono", 9056)
value

64023

In [18]:
k_list = ['a', 'b', 7]
v_list = ['some value', [1, 2, 3, 4], 'an integer']

In [21]:
mapping = {}
for k, v in zip(k_list, v_list):
    mapping[k] = v


<class 'dict'>


In [48]:
words = ['apple', 'bat', 'bar', 'atom', 'book']
by_letter = {}
    
for word in words:
    letter = word[0]
    if letter not in by_letter:
        by_letter[letter] = [word]
    else: 
        by_letter[letter].append(word)

by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

In [50]:
for word in words:
    letter = word[0]
    by_letter.setdefault(letter,[]).append(word)

by_letter

{'a': ['apple', 'atom', 'apple', 'atom'],
 'b': ['bat', 'bar', 'book', 'bat', 'bar', 'book']}

In [54]:
hash('string')

3593915786120885642

In [63]:
hash(2)

2

In [65]:
hash((2,5,7,8))

-2141743049507838393

In [ ]:
result = []
for val in collection:
    if condition:
        result.append(expr)

In [69]:
strings = ['a', 'as', 'bat', 'car', 'dove', 'python']

[x.upper() for x in strings if len(x) > 2]

['BAT', 'CAR', 'DOVE', 'PYTHON']

In [73]:
all_data = [['John', 'Emily', 'Michael', 'Mary', 'Steven'], ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]

names_of_interest = []
for names in all_data:
    enough_es = [name for name in names if name.count('e') >= 2]
    names_of_interest.extend(enough_es)

names_of_interest

['Steven']

In [75]:
result = [name for names in all_data for name in names if name.count('e') >= 2]
result

['Steven']

In [78]:
def my_function(x, y, z=1.5):
    if z > 1:
        return z * (x + y)
    else:
        return z / (x + y)

h = my_function(x=3, y=5)
h

12.0

In [79]:
def attempt_float(x):
    try:
        return float(x)
    except:
        return x

attempt_float('1.2345')
attempt_float('something')

'something'

In [80]:
f = open(path, 'w')

try:
    write_to_file(f)
except:
    print('Failed')
else:
    print('Succeeded')
finally:
    f.close()

NameError: name 'path' is not defined

In [89]:
import numpy as np
np.bincount
#from numpy import array, arange

In [87]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [97]:
##inheritance

class LivingBeing():
    """Father/Mother class"""
    def __init__(self, species, born_date, procreate_ability=True, aging_disease=True):
        self.is_living = True
        self.species = species
        self.procreate_ability = procreate_ability
        self.aging_disease = aging_disease
        self.born_date = born_date
    
    def living_being_function(self):
        print("I'M A LIVING BEING!")


In [100]:
Rochi = LivingBeing(species="Humano", born_date="30/11/1978")
print(Rochi.species)

Humano


In [ ]:
class Human(LivingBeing):
    """Children class"""
    ##Humano v a atener todos los atributos de la clase de Padre/Madre/ Incluido la funcion.LivingBeing.
    ##agrega nuevos atributos.
    

In [3]:
import numpy as np
arr = np.empty((8, 4)) 
for i in range(8):
    arr[i] = i
arr


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [7]:
arr.T

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27],
       [ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31]])

In [9]:
arr = np.random.randn(6, 3)
arr

array([[-1.23403839,  0.9386931 ,  1.02026948],
       [-0.92818565, -0.10321826,  0.51637164],
       [ 0.03159333,  0.61261155, -1.40370071],
       [-1.37287969, -1.78695471, -0.60442018],
       [ 1.97175846,  1.42325215, -1.3820494 ],
       [-1.71508409,  0.84689017,  0.13355363]])

In [20]:
arr.swapaxes(6, 3)
arr

AxisError: axis1: axis 3 is out of bounds for array of dimension 2

In [10]:
np.dot(arr.T, arr)

##Simple transposing with .T is a special case of swapping axes. ndarray has the method swapaxes, which takes a pair of axis numbers and switches the indicated axes to rearrange the data:

array([[11.09952096,  2.76387227, -3.90701514],
       [ 2.76387227,  7.20316844, -0.72933038],
       [-3.90701514, -0.72933038,  5.57118605]])

In [21]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)

[-1.59671762 -0.66691994  1.99884972 -1.28173016  1.00244853 -0.71749598
  1.78449104 -0.30028592]
[ 1.91810047  1.78312603  0.76169595 -0.71059951  1.8672342   1.13526498
  0.54972545  0.16678675]


In [22]:
np.maximum(x, y)

array([ 1.91810047,  1.78312603,  1.99884972, -0.71059951,  1.8672342 ,
        1.13526498,  1.78449104,  0.16678675])

In [23]:
rng = np.random.RandomState(1234)
rng.randn(10)


array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [28]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)
    
print(position)

28


In [31]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()
print(steps)
print(walk)

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1 -1  1  1  1  1 -1 -1 -1
  1 -1 -1 -1 -1  1  1  1 -1 -1 -1  1 -1  1  1 -1  1 -1  1  1  1  1  1 -1
  1  1  1  1 -1  1  1  1  1  1 -1  1 -1 -1  1 -1  1 -1  1  1 -1 -1  1  1
 -1 -1 -1 -1 -1  1  1 -1  1  1  1 -1  1  1  1 -1 -1 -1  1 -1 -1  1  1  1
  1  1 -1 -1  1 -1 -1  1 -1 -1  1  1 -1  1  1 -1  1  1  1  1  1 -1 -1  1
 -1  1 -1 -1  1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1 -1 -1  1 -1  1 -1  1 -1
  1 -1  1  1 -1  1  1 -1 -1  1  1 -1 -1 -1  1  1 -1 -1 -1  1 -1 -1 -1 -1
  1 -1  1 -1 -1 -1 -1 -1 -1 -1  1 -1  1 -1  1 -1 -1 -1  1  1 -1  1 -1  1
 -1  1  1 -1  1  1  1  1 -1 -1 -1  1 -1 -1  1 -1  1 -1 -1  1  1  1  1 -1
  1 -1  1 -1 -1 -1  1  1  1 -1  1  1 -1 -1 -1 -1  1 -1  1  1 -1 -1  1 -1
 -1  1  1  1 -1  1 -1 -1  1  1 -1 -1 -1 -1  1  1  1 -1 -1  1 -1 -1  1 -1
 -1 -1 -1 -1 -1  1 -1 -1  1 -1 -1  1  1  1  1  1  1 -1  1 -1  1 -1  1  1
  1 -1 -1 -1  1 -1 -1 -1  1  1 -1 -1  1 -1 -1 -1  1  1 -1 -1  1 -1 -1  1
 -1 -1  1 -1  1  1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1

In [7]:
walk.max()
walk.min()

NameError: name 'walk' is not defined

In [16]:
class Puerta:
    def __init__(self):
        pass

In [33]:
class Dog:
    
    def __init__(self, name, age):
        self.name = name
        self.age = str(age)
    
    def __str__(self):
        return "Amamos a nuestra mascota " + self.name + "que tiene " + self.age
        
    def show_attributes(self):
        print(self.name + "tiene" + self.age + " años")

Dory = Dog(name="Dory", age=5)
Dory.show_attributes()
print(Dory)


Dorytiene5 años
Amamos a nuestra mascota Doryque tiene 5


In [3]:
import numpy as np 

In [2]:
import matplotlib.pyplot as plt

In [8]:
import random
X = random.randint(2, 10)
X

4

In [9]:
import pandas as pd
import json

df = pd.read_csv('http://pastebin.com/raw/7L86m9R2', \
                 header=None, index_col=0, names=['data'])

In [10]:
df

data
0   {"idTiers": "107330", "idAnnonce": "113201527"...
1   {"idTiers": "170361", "idAnnonce": "115282633"...
2   {"idTiers": "153796", "idAnnonce": "114652905"...
3   {"idTiers": "119592", "idAnnonce": "114171943"...
4   {"idTiers": "16121", "idAnnonce": "99860973", ...
5   {"idTiers": "67103", "idAnnonce": "114846757",...
6   {"idTiers": "67103", "idAnnonce": "114846759",...
7   {"idTiers": "67103", "idAnnonce": "114846761",...
8   {"idTiers": "67103", "idAnnonce": "114846765",...
9   {"idTiers": "67103", "idAnnonce": "114846767",...
10  {"idTiers": "67103", "idAnnonce": "114846769",...
11  {"idTiers": "67103", "idAnnonce": "114846771",...
12  {"idTiers": "67103", "idAnnonce": "114846773",...
13  {"idTiers": "67103", "idAnnonce": "114846775",...
14  {"idTiers": "67103", "idAnnonce": "114846779",...
15  {"idTiers": "17783", "idAnnonce": "111034595",...
16  {"idTiers": "24680", "idAnnonce": "112983375",...
17  {"idTiers": "23883", "idAnnonce": "114908405",...
18  {"idTiers": "131429", "idAnnonce": "114888951"...
19  {"idTiers": "108452", "idAnnonce": "112978263"...

In [11]:
pd.io.json.json_normalize(df.data.apply(json.loads))

idTiers  idAnnonce idAgence idPublication idTypeTransaction idTypeBien  \
0   107330  113201527    90338        466858                 2          1   
1   170361  115282633   114072        550168                 2          1   
2   153796  114652905   102645        507321                 2          1   
3   119592  114171943    82251        428258                 8          1   
4    16121   99860973    41743        192929                 2          1   
5    67103  114846757    68466      30068466                 6          1   
6    67103  114846759    68466      30068466                 6          1   
7    67103  114846761    68466      30068466                 6          1   
8    67103  114846765    68466      30068466                 6          1   
9    67103  114846767    68466      30068466                 6          1   
10   67103  114846769    68466      30068466                 6          1   
11   67103  114846771    68466      30068466                 6          1   
12   67103  114846773    68466      30068466                 6          1   
13   67103  114846775    68466      30068466                 6          1   
14   67103  114846779    68466      30068466                 6          1   
15   17783  111034595    42892        231281                 2          1   
16   24680  112983375    55939        277242                 2          9   
17   23883  114908405    47803        229441                 2          1   
18  131429  114888951   104711        516104                 2          1   
19  108452  112978263    77178        407814                 8          1   

            dtFraicheur           dtCreation                 titre  \
0   2016-11-25T17:32:45  2016-10-05T14:55:00  Appartement 3 pièces   
1   2016-12-16T16:55:00  2016-12-13T12:57:00  Appartement 5 pièces   
2   2016-12-11T15:30:00  2016-11-23T09:09:00  Appartement 4 pièces   
3   2016-12-15T23:19:00  2016-11-05T20:18:00  Appartement 9 pièces   
4   2016-12-16T02:50:00  2015-06-11T14:50:00  Appartement 3 pièces   
5   2016-12-15T20:06:00  2016-11-29T20:06:00  Appartement 3 pièces   
6   2016-12-15T20:06:00  2016-11-29T20:06:00  Appartement 3 pièces   
7   2016-12-15T20:06:00  2016-11-29T20:06:00  Appartement 2 pièces   
8   2016-12-15T20:06:00  2016-11-29T20:06:00  Appartement 3 pièces   
9   2016-12-15T20:06:00  2016-11-29T20:06:00  Appartement 2 pièces   
10  2016-12-15T20:06:00  2016-11-29T20:06:00  Appartement 3 pièces   
11  2016-12-15T20:06:00  2016-11-29T20:06:00  Appartement 3 pièces   
12  2016-12-15T20:06:00  2016-11-29T20:06:00  Appartement 3 pièces   
13  2016-12-15T20:06:00  2016-11-29T20:06:00  Appartement 3 pièces   
14  2016-12-15T20:06:00  2016-11-29T20:06:00  Appartement 4 pièces   
15  2016-11-25T17:32:45  2016-11-04T09:37:00  Appartement 3 pièces   
16  2016-12-16T00:39:00  2016-09-28T13:49:00                  Loft   
17  2016-12-16T13:43:00  2016-12-01T12:06:00       Duplex 5 pièces   
18  2016-12-10T00:06:00  2016-11-30T23:47:00  Appartement 6 pièces   
19  2016-12-14T01:10:00  2016-09-28T09:56:00  Appartement 6 pièces   

                                         libelle  ... contact.idPublication  \
0                           Appartement 3 pièces  ...                466858   
1                                       5 pièces  ...                550168   
2                                       4 pièces  ...                507321   
3                                       9 pièces  ...                428258   
4                                 Lyon 1er Saone  ...                192929   
5                           Appartement 3 pièces  ...              30068466   
6                           Appartement 3 pièces  ...              30068466   
7                           Appartement 2 pièces  ...              30068466   
8                           Appartement 3 pièces  ...              30068466   
9                           Appartement 2 pièces  ...              30068466   
10                          Appartement 3 piè