1. 

En el archivo "logistic_regression_df_class" hemos visto un ejemplo multiclase. Elimina del dataframe todas las filas que se correspondan con la clase valor "1".

Ahora, realiza el ejercicio con el nuevo dataframe:

- ¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?

LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (toca, modifica, prueba) las variables y comenta si hay alguna de ellas que, modificándola, mejore el porcentaje de acierto del problema.

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html


In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline

In [71]:
dataframe = pd.read_csv("../data/usuarios_win_mac_lin.csv")
dataframe.head()

duracion  paginas  acciones  valor  clase
0       7.0        2         4      8      2
1      21.0        2         6      6      2
2      57.0        2         4      4      2
3     101.0        3         6     12      2
4     109.0        2         6     12      2

In [72]:
dataframe.describe()

duracion     paginas    acciones       valor       clase
count  170.000000  170.000000  170.000000  170.000000  170.000000
mean   111.075729    2.041176    8.723529   32.676471    0.752941
std    202.453200    1.500911    9.136054   44.751993    0.841327
min      1.000000    1.000000    1.000000    1.000000    0.000000
25%     11.000000    1.000000    3.000000    8.000000    0.000000
50%     13.000000    2.000000    6.000000   20.000000    0.000000
75%    108.000000    2.000000   10.000000   36.000000    2.000000
max    898.000000    9.000000   63.000000  378.000000    2.000000

In [73]:
# Elimina del dataframe todas las filas que se correspondan con la clase valor "1".
dataframe['clase']

0      2
1      2
2      2
3      2
4      2
      ..
165    0
166    0
167    0
168    0
169    0
Name: clase, Length: 170, dtype: int64

In [74]:
dataframe

duracion  paginas  acciones  valor  clase
0         7.0        2         4      8      2
1        21.0        2         6      6      2
2        57.0        2         4      4      2
3       101.0        3         6     12      2
4       109.0        2         6     12      2
..        ...      ...       ...    ...    ...
165      13.0        1         7     42      0
166      12.0        1         2      6      0
167      13.0        1         3      9      0
168      13.0        1         7     28      0
169      12.0        1         6     18      0

[170 rows x 5 columns]

In [75]:
dataframe.shape

(170, 5)

In [76]:
dataframe.clase.value_counts()

0    86
2    44
1    40
Name: clase, dtype: int64

In [77]:
dataframe.columns

Index(['duracion', 'paginas', 'acciones', 'valor', 'clase'], dtype='object')

In [102]:
cero = dataframe.loc[dataframe['clase'] == 0]
cero

duracion  paginas  acciones  valor  clase
49        1.0        2        18     36      0
50        2.0        2        20    120      0
51        7.0        1         7     28      0
52       10.0        2        18     54      0
53       12.0        2        20     40      0
..        ...      ...       ...    ...    ...
165      13.0        1         7     42      0
166      12.0        1         2      6      0
167      13.0        1         3      9      0
168      13.0        1         7     28      0
169      12.0        1         6     18      0

[86 rows x 5 columns]

In [99]:
uno = dataframe.loc[dataframe['clase'] == 1]
uno

duracion  paginas  acciones  valor  clase
17     21.000        2         4     12      1
18     33.000        2         8     48      1
19     49.000        2         8     32      1
20     74.000        2         6     18      1
21     93.000        2        12     96      1
22    145.000        2        10     30      1
23    152.000        2         4     20      1
24    208.000        2        10     30      1
25    219.000        3         9     54      1
26    235.000        6        12     96      1
27    257.000        2        12     48      1
28    266.000        2         4     12      1
29    275.000        4        24    144      1
30    355.000        2         4     16      1
31    473.000        3         6     30      1
32    485.000        2         6     30      1
33    652.000        2         6     24      1
34    848.000        3        18     54      1
40     11.000        2        10     40      1
41     31.000        2         6     30      1
42     51.000        2         4     20      1
43     89.000        3        18    144      1
44    112.000        2         6     18      1
45    278.000        2         4     28      1
46    674.000        3        18     72      1
47      1.088        2         8     64      1
48      1.294        2         6     18      1
96     13.000        1         2     16      1
98     12.000        1         6     48      1
99     13.000        1         4     12      1
100    12.000        1         6     24      1
101    12.000        1         5     35      1
102    13.000        1         6     36      1
103    13.000        1         5     20      1
104    12.000        1         3     12      1
105    13.000        1         3     18      1
106    12.000        1         6     24      1
107    13.000        1         6     18      1
108    12.000        1         6     24      1
109    11.000        1         5     40      1

In [100]:
uno.shape

(40, 5)

In [106]:
frames = [cero, uno]

In [107]:
result = pd.concat(frames)

In [108]:
result

duracion  paginas  acciones  valor  clase
49        1.0        2        18     36      0
50        2.0        2        20    120      0
51        7.0        1         7     28      0
52       10.0        2        18     54      0
53       12.0        2        20     40      0
..        ...      ...       ...    ...    ...
105      13.0        1         3     18      1
106      12.0        1         6     24      1
107      13.0        1         6     18      1
108      12.0        1         6     24      1
109      11.0        1         5     40      1

[126 rows x 5 columns]

Ahora, realiza el ejercicio con el nuevo dataframe:

¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?
LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (toca, modifica, prueba) las variables y comenta si hay alguna de ellas que, modificándola, mejore el porcentaje de acierto del problema.

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [109]:
X = np.array(result.drop(['clase'], 1))
y = np.array(result['clase'])
X.shape

(126, 4)

In [110]:
model = linear_model.LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [111]:
y.shape

(126,)

In [112]:
predictions = model.predict(X)
print(predictions)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 1 1 1 1 1 1 0 0 0 0 1 0 1 0
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0]


In [113]:
model.score(X,y)

0.7380952380952381

EL MODELO TIENE UN SCORE MAS BAJO CON UNA CLASE MENOS. ESTA PEOR ENTRENADO.

In [115]:
validation_size = 0.20
seed = 7
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, y, test_size=validation_size, random_state=seed)

In [116]:
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=10, random_state=seed) #Parte los datos en 10 trozos para usar validación cruzada / cross validation
cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
print(msg)

Logistic Regression: 0.760000 (0.091652)


In [117]:
predictions = model.predict(X_test)
print(accuracy_score(Y_test, predictions))

0.6538461538461539


EL PORCENTAJE DE ACIERTO ES INFERIOR CUANDO ELIMINAMOS LA CLASE 1

In [118]:
print(confusion_matrix(Y_test, predictions))

[[14  2]
 [ 7  3]]


In [119]:
Y_test

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0])

In [120]:
Y_test.shape

(26,)

In [121]:
acierto = accuracy_score(Y_test, predictions)
error = 1 - acierto
print('Acierto', round(acierto*100, 2))
print('El error es de: ', round(error*100, 2), '%')

Acierto 65.38
El error es de:  34.62 %


In [127]:
#clasificacion de uevos registros

X_new = pd.DataFrame({'duracion': [18], 'paginas': [9], 'acciones': [5], 'valor': [12]})
model.predict(X_new)

array([1])

In [128]:
X_new

duracion  paginas  acciones  valor
0        18        9         5     12